# Generated by Django 3.1 on 2020-08-13 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_address_order_payment_productorder_refund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_data',
            new_name='order_date',
        ),
    ]
